name: wesing_mvp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  just_audio: ^0.9.36
  cached_network_image: ^3.3.1
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  record: ^5.0.5
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  record_linux: 0.7.0
  record_platform_interface: 1.0.1
